version: "3.9" # not required
services:
  api:
    build:
      context: ./Server
    container_name: api
    ports:
      - 127.0.0.1:2999:80
    depends_on:
      elastic:
        condition: service_healthy
    healthcheck:
          test: ["CMD", "wget", "http://localhost:80/health"]
          interval: 30s
  
  elastic: # service name (also used as host name)
    container_name: elastic
    build:
      context: ./Elastic
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 127.0.0.1:9200:9200
    volumes:
     - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  webapp:
    build:
      context: ./Client
    container_name: webapp
    volumes:
      - type: bind
        source: ./Client/src
        target: /usr/src/webapp/src
      - type: bind
        source: ./Client/static
        target: /usr/src/webapp/static
    ports:
      - 127.0.0.1:5173:5173
    links:
      - api

